repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies:
          - lxml==5.2
          - types-lxml
          - pillow==10.3
          - types-pillow
          - htpy==25.8.1
          - pytest
