name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Sync Deps
        run: uv sync --all-extras --dev

      - name: Lint & format via Ruff
        run: uv run ruff check && uv run ruff format

      - name: Type check
        run: uv run mypy

      - name: Testing Suite
        run: uv run pytest
